# -*- coding: utf-8 -*-
"""Knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W37st10JED_q29spXhVJU5_isYTBJ-NL
"""

from google.colab import drive
drive.mount('/content/gdrive')

from numpy import genfromtxt
data_path = '/content/gdrive/MyDrive/diabetes.csv'
my_data = genfromtxt(data_path, delimiter=',')

#my_data.shape
type(my_data)

data = my_data.tolist()
for i in range(5):
  print(data[i])
type(data)

import random
import math
import numpy as np


def mejority(count,count1,count2):
  if (count>count1 and count > count2):
      return 0
  elif (count1>count and count1>count2):
      return 1
  else:
      return 2    




def knn_classification(data,Train_set,Val_set,Test_set):
  k = 6
  c_val = 0
  v_count = 0
  for v in Val_set:
    count = 0
    count1 = 0
    count2 = 0
    l = []
    for t in Train_set:
      a = np.array(v[:4])
      b = np.array(t[:4])
      distance = np.linalg.norm(a-b)
      tmp = [distance,t[-1]]
      l.append(tmp)
    l.sort()
    l1 = l[:k]
    for x in l1:
      if (x[-1] == 0):
        count+=1
      elif (x[-1] == 1):
        count1+=1
      else:
        count2+=1
    m = mejority(count,count1,count2)
    if (m == v[-1]):
      c_val+=1
    v_count+=1
  
  validation_accuracy = (c_val)/(v_count) * 100
  print(validation_accuracy)

def average(l,k):
    l = l[:k]
    sum = 0
    for i in range(k):
        sum += l[i][1]

    return sum/k    

def knn_regression(data,Train_set,Val_set,Test_set):
  k=4
  error = 0
  v_count = 0
  for v in Val_set:
    count = 0
    count1 = 0
    count2 = 0
    l = []
    for t in Train_set:
      a = np.array(v[:4])
      b = np.array(t[:4])
      distance = np.linalg.norm(a-b)
      tmp = [distance,t[-1]]
      l.append(tmp)
    l.sort()
    avg = average(l,k)
    error = error+(v[-1]-avg)**2
    v_count+=1
  Mean_Squared_Error = error/v_count
  print(Mean_Squared_Error)


Train_set = []
Val_set = [] 
Test_set = []

for S in data:
  R = random.uniform(0, 1)
  if R>=0 and R<=0.7:
   Train_set.append(S)
  elif R>0.7 and R<=0.85:
   Val_set.append(S)
  else:
   Test_set.append(S)   
#knn_classification(data,Train_set,Val_set,Test_set)
knn_regression(data,Train_set,Val_set,Test_set)





